language: cpp

dist: trusty

sudo: required

compiler:
  - gcc
  - clang

os:
  - linux

env:
  matrix:
    - FLAGS="-DCMAKE_BUILD_TYPE=Debug"
    - FLAGS="-DCMAKE_BUILD_TYPE=Release"

before_install:
 - sudo add-apt-repository --yes ppa:beineri/opt-qt58-trusty
 - sudo apt-get update -qq

install:
 - sudo apt-get -qy install qt5-qmake qtbase5-dev libqt5xmlpatterns5-dev build-essential pngcrush qtmultimedia5-dev
  
script:
  - export QT_SELECT=qt5
  - source /opt/qt58/bin/qt58-env.sh
  - /opt/qt58/bin/qmake PREFIX=/usr
  - /opt/qt58/bin/qmake --version
  - qmake --version
  - mkdir build
  - cd build
  - cmake --version
  - cmake -trace --warn-uninitialized --warn-unused_vars -Wdev -G "Unix Makefiles" .. -DCMAKE_INSTALL_PREFIX=../install $FLAGS
  - make && ctest && make install && cpack -G "TGZ"

addons:
  apt:
    packages:
    - cmake
    - cmake-data

